[package]
name = "ab_glyph"
version = "0.0.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
description = "Glyph stuff"
repository = "https://github.com/alexheretic/ab-glyph"
keywords = ["text", "ttf", "otf", "font", "truetype", "opentype"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
ttf-parser = { version = "0.5", default-features = false }
ab_glyph_rasterizer = { path = "../rasterizer", default-features = false }
# no_std float stuff
libm = { version = "0.2.1", optional = true }

[dev-dependencies]
# don't add any, instead use ./dev

[features]
default = ["std"]
# Activates usage of std.
std = ["ttf-parser/default", "ab_glyph_rasterizer/default"]
# Uses libm when not using std. This needs to be active in that case.
libm-math = ["libm", "ab_glyph_rasterizer/libm"]
